project:
  type: website
  output-dir: docs
  resources:
    - Images/

website:
  title: "Cáit O'Reilly"
  site-url: https://cait-oreilly.github.io/eportfolio
  navbar:
    logo: /eportfolio/Images/logo.png
    background: dark
    foreground: light
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "About Me"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Contact"
        href: contact.qmd
  page-footer:
    left: "2026 Cáit O'Reilly"
    right:
      - icon: github
        href: https://github.com/cait-oreilly
      - icon: linkedin
        href: https://www.linkedin.com/in/yourname/

format:
  html:
    theme:
      light:
        - lux
        - styles_light.scss
      dark:
        - lux
        - styles_dark.scss
    mainfont: Arimo
    toc: true
    page-layout: full

