project:
  type: website
  output-dir: docs
  resources:
    - Images/
    - Images/favicon.png
    - Images/index-pic.png

website:
  title: "Cáit O'Reilly"
  site-url: https://cait-oreilly.github.io/eportfolio
  favicon: "Images/favicon.png"
  navbar:
    logo: Images/Logo.png
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "About Me"
        href: about.qmd
      - text: "Projects"
        href: projects/index.qmd
      - text: "Reflection"
        href: projects/list/critical-reflection.qmd
      - text: "Skills"
        href: achievements.qmd
      - text: "CV"
        href: projects_files/CV.pdf
        target: _blank
      - text: "Contact"
        href: contact.qmd
      - icon: github
        href: https://github.com/cait-oreilly
  page-footer:
    left: "Copyright 2026, Cáit O'Reilly"
    center: "Built with [Quarto](https://quarto.org)"
    right:
      - icon: github
        href: https://github.com/cait-oreilly
      - icon: linkedin
        href: https://www.linkedin.com/in/cait-oreilly-ogrady

format:
  html:
    mermaid:
      theme: dark
    theme:
      light:
        - lux
        - styles_light.scss
      dark:
        - lux
        - styles_dark.scss
    mainfont: Arimo
    toc: true
    page-layout: full